### PR TITLE
:heavy_dollar_sign: Give more weight to terms in name

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
See [here](https://trello.com/c/8li7M47r/131-refined-search-results) for rational and examples

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-db-pr-28.dev.c2s.nhschoices.net](http://profiles-db-pr-28.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-db-pr-28.dev.c2s.nhschoices.net](http://profiles-db-pr-28.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-db-pr-28.dev.c2s.nhschoices.net](http://profiles-db-pr-28.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-db-pr-28.dev.c2s.nhschoices.net](http://profiles-db-pr-28.dev.c2s.nhschoices.net)

**Comment by neilbmclaughlin** [comment]
Put the WIP label back on to allow Nick to be able to review the results in the (manually) deployed preview.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-db-pr-28.dev.c2s.nhschoices.net](http://profiles-db-pr-28.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://profiles-db-pr-28.dev.c2s.nhschoices.net](http://profiles-db-pr-28.dev.c2s.nhschoices.net)

**Pull request merged**
