### PR TITLE
DO NOT MERGE - Needs to go out with changes on gp-finder

### PR DESCRIPTION
**Pull request by beseven**

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
I've been looking at tightening up the results as well as adding GP names and have been experimenting with this code:

```
...
&& mongo profiles --eval "db.gps.find().snapshot().forEach(function (gp) { gp.searchWords = gp.doctors.concat([gp.address.addressLines[0], gp.name]).join(' ').toLowerCase().replace(/[^\w\s]/g,'').replace(/\s+/g,' ').split(' ').fil    ter(function(item, pos, self) { return self.indexOf(item) == pos; }).join(' '); db.gps.save(gp);} )" \
&& mongo profiles --eval "db.gps.createIndex({ 'searchWords': 'text'}, { 'default_language': 'none' }, { 'name': 'SearchIndex' })" \
...
```
The key differences are:
1. only using the searchWords field in indexing. Adding the gp.name to the search words and also indexing by gp.name (as in the current version of the code) is skewing the results I think.
1. turning off stemming by setting default_language to 'none'. I think using stemming for nouns is returning false positives.

Any thoughts?

**Comment by neilbmclaughlin** [comment]
The reason for adding the GP names to the search words rather than being indexed directly is to remove duplicates which prevents a search for 'Elizabeth Beech' returning results where a surgery with lots of GP's with a first name of  Elizabeth being ranked higher than one with a GP called 'Elizabeth Beech'

**Comment by beseven** [comment]
Good point, trying to test that locally now, however, it seems that we might need to change the way we search too?
Are we trying to amend the first line of the address in this too?

**Comment by neilbmclaughlin** [comment]
Only in that it seemed easiest to replace `gp.address.addressLines.concat` with `gp.doctors.concat`.

If you'd prefer to do the work incrementally and split it into separate PR's then I'm happy.

**Comment by beseven** [comment]
Nope this is fine, I'm just wanting to understand how this change will affect the previous search. The aim is to improve on the previous search.

**Pull request merged**
